version: "3.9"

services:
  backend:
    build: ./backend

    container_name: smart-leads-backend

    ports:
      - "5000:5000"

    environment:
      PORT: ${PORT}
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}

    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend

    container_name: smart-leads-frontend

    ports:
      - "5173:5173"

    depends_on:
      - backend

    volumes:
      - ./frontend:/app
      - /app/node_modules
